package com.edutecno.controller;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.edutecno.model.Usuario;

/**
 * Servlet implementation class UsuarioServlet
 */
@WebServlet("/UsuarioServlet")
public class UsuarioServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public UsuarioServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		List<Usuario> usuarios = new ArrayList<>();
		
		// conexion a la base de datos y ejecucion de la sentencia
		try {
			Class.forName("oracle.jdbc.driver.OracleDriver");
			//Class.forName("com.mysql.cj.jdbc.Driver");
			
			//String url = "jdvc:oracle:thin:@localhost:1521:xe" COn SID xe
			String url = "jdbc:oracle:thin:@localhost:1521/FREEPDB1";
			Connection conn = DriverManager.getConnection(url, "JIOH", "1160");
			Statement stmt = conn.createStatement();
			//Descomentar para crear la tabla
//			stmt.executeUpdate("DROP TABLE IF EXISTS USUARIO");
//			stmt.executeUpdate("CREATE TABLE USUARIO (ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
//					+ "NOMBRE VARCHAR2(50) NOT NULL, APELLIDO VARCHAR2(50) NOT NULL, USERNAME VARCHAR2(50) NOT NULL, PASSWORD VARCHAR2(50 NOT NULL, "
//					+ "EMAIL VARCHAR2(50) NOT NULL UNIQUE )");
//			stmt.executeUpdate("INSERT INTO USUARIO (NOMBRE, APELLIDO, USERNAME, PASSWORD, EMAIL) "
//					+ "VALUES('Juan', 'Oh', 'jioh', '1160', 'jioh@mail.com')");
//			stmt.executeUpdate("INSERT INTO USUARIO (NOMBRE, APELLIDO, USERNAME, PASSWORD, EMAIL) "
//					+ "VALUES('Marcelo', 'Toro', 'mtoro', '1234', 'mtoro@mail.com')");
			ResultSet rs = stmt.executeQuery("SELECT * FROM USUARIO");
			
			while(rs.next()) {
				Usuario usuario = new Usuario();
				
				usuario.setId(rs.getInt("id"));
				usuario.setNombre(rs.getString("nombre"));
				usuario.setApellido(rs.getString("apellido"));
				usuario.setUsername(rs.getString("username"));
				usuario.setPassword(rs.getString("password"));
				usuario.setEmail(rs.getString("email"));
				
				usuarios.add(usuario);
			}
			
//			for(Usuario usuario: usuarios) {
//				System.out.println(usuario);
//			}
			
			//usuarios.stream().forEach(System.out::println);
			
			request.setAttribute("usuarios", usuarios);
			request.getRequestDispatcher("listarUsuario.jsp").forward(request, response);
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
		
	
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub

		String nombre = request.getParameter("nombre");
		String apellido  = request.getParameter("apellido");
		String username = request.getParameter("username");
		String password = request.getParameter("password");
		String email = request.getParameter("email");
//		System.out.println(nombre);
		
		try {
			Class.forName("oracle.jdbc.driver.OracleDriver");
			String url = "jdbc:oracle:thin:@localhost:1521/FREEPDB1";
			Connection conn = DriverManager.getConnection(url, "JIOH", "1160");
			Statement stmt = conn.createStatement();
			if(nombre != "" && apellido != "" && username != "" && password != "" && email != "") {
				String query = String.format("INSERT INTO USUARIO (NOMBRE, APELLIDO, USERNAME, PASSWORD, EMAIL) "
						+ "VALUES('%s', '%s', '%s', '%s', '%s') ", nombre, apellido, username, password, email);
				
				System.out.println(query);
				stmt.executeUpdate(query);
				request.getRequestDispatcher("crearUsuario.jsp").forward(request, response);
			} 
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
	}

}
